name: Go

on:
  push:
    branches: [ main ]
    tags: 
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.24
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: go build -v .

    - name: Run Unit tests
      run: go test -race ./...
